### ISSUE TITLE
Hotkey to cycle through map colors

### ISSUE THREAD

**Issue by nathanrdodson** [maxxxxxdlp/eecs-448-pixelland#49]
On the standard Pixelland rainbow world, there could be a hotkey (ie, Space) which would cycle through different color variations and re-render the map as such.

**Comment by maxxxxxdlp** [comment]
Cool idea!
To take it even further, instead of a hotkey, there could be some special blocks all over the map that do that

**Comment by nathanrdodson** [comment]
I love it! I think that is the way to go.

**Comment by maxxxxxdlp** [comment]
Fixed by @nathanrdodson in 3f7b17b
